"""EviLearn Backend — FastAPI Application.

Main API server implementing claim-based knowledge validation endpoints.
All data is validated via Pydantic schemas BEFORE storage or response.
Embeddings are generated via EmbeddingService (LLM API), NOT ChromaDB.
"""

import os
import uuid
import json
from typing import Optional

from fastapi import FastAPI, UploadFile, File, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import ValidationError

from .config import settings
from .schemas import (
    ProcessInputRequest,
    ProcessInputResponse,
    FeedbackRequest,
    FeedbackResponse,
    EditClaimRequest,
    DocumentResponse,
    HistoryResponse,
    HistorySession,
    HistoryClaimItem,
    HistoryFeedbackItem,
    ClaimResult,
    EvidenceItem,
    ErrorResponse,
    EvaluateReasoningRequest,
    EvaluateReasoningResponse,
    WeaknessItem,
    RobustnessSummary,
)
from .data_layer.document_processor import DocumentProcessor
from .data_layer.chunker import TextChunker
from .data_layer.vector_store import VectorStore
from .data_layer.database import Database
from .data_layer.embedding_service import EmbeddingService
from .ai_engine.pipeline import ValidationPipeline


# --- Initialize Application ---

app = FastAPI(
    title="EviLearn API",
    description="Claim-based knowledge validation system API",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Initialize Services ---

db = Database(db_path=settings.SQLITE_DB_PATH)
doc_processor = DocumentProcessor()
chunker = TextChunker(chunk_size=500, chunk_overlap=50)
vector_store = VectorStore(
    persist_directory=settings.CHROMA_PERSIST_DIR,
)

# Initialize LLM client (required for embeddings and optional for agents)
llm_client = None
if settings.LLM_API_KEY:
    try:
        if settings.LLM_PROVIDER == "groq":
            from groq import Groq
            llm_client = Groq(api_key=settings.LLM_API_KEY)
        else:
            from openai import OpenAI
            llm_client = OpenAI(api_key=settings.LLM_API_KEY)
    except ImportError:
        pass

# Initialize EmbeddingService — embeddings come ONLY from LLM API
embedding_service = EmbeddingService(
    llm_client=llm_client,
    provider=settings.LLM_PROVIDER,
)

pipeline = ValidationPipeline(
    vector_store=vector_store,
    llm_client=llm_client,
    embedding_service=embedding_service,
)


# --- Health Check ---

@app.get("/")
def health_check():
    """Health check endpoint."""
    return {"status": "ok", "service": "EviLearn API", "version": "1.0.0"}


# --- Document Endpoints ---

@app.post("/upload-documents", response_model=DocumentResponse)
async def upload_document(file: UploadFile = File(...)):
    """Upload and process a document (PDF or text file).

    Executes: Upload → Extract → Chunk → Embed (via LLM API) → Store in ChromaDB
    Embeddings are generated by EmbeddingService, NOT by ChromaDB.
    """
    # Validate file extension
    file_name = file.filename or "unknown"
    ext = os.path.splitext(file_name)[1].lower()
    if ext not in settings.ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file type: {ext}. Allowed: {settings.ALLOWED_EXTENSIONS}",
        )

    # Read file
    file_bytes = await file.read()
    if not file_bytes:
        raise HTTPException(status_code=400, detail="Uploaded file is empty.")

    # Check file size
    if len(file_bytes) > settings.MAX_FILE_SIZE_MB * 1024 * 1024:
        raise HTTPException(
            status_code=400,
            detail=f"File exceeds maximum size of {settings.MAX_FILE_SIZE_MB}MB.",
        )

    # Generate document ID
    document_id = DocumentProcessor.generate_document_id()

    # Store document record
    db.insert_document(document_id=document_id, file_name=file_name)

    try:
        # Extract text
        if ext == ".pdf":
            pages = DocumentProcessor.extract_text_from_pdf(file_bytes)
        else:
            content = file_bytes.decode("utf-8", errors="ignore")
            pages = DocumentProcessor.extract_text_from_plain(content)

        # Chunk text
        chunks = chunker.chunk_pages(pages, document_id)

        # Generate embeddings via LLM API (NOT ChromaDB)
        chunk_texts = [c["chunk_text"] for c in chunks]
        embeddings = embedding_service.embed_texts(chunk_texts)

        # Store in ChromaDB with pre-computed embeddings
        vector_store.add_chunks(
            chunk_ids=[c["chunk_id"] for c in chunks],
            documents=chunk_texts,
            metadatas=[
                {"page_number": c["page_number"], "document_id": c["document_id"]}
                for c in chunks
            ],
            embeddings=embeddings,
        )

        # Store chunks in SQLite
        db.insert_chunks(chunks)

        # Update status
        db.update_document_status(document_id, "ready")

        return DocumentResponse(
            document_id=document_id,
            file_name=file_name,
            status="ready",
            page_count=len(pages),
            message=f"Document processed successfully. {len(chunks)} chunks created.",
        )

    except ValueError as e:
        db.update_document_status(document_id, "failed")
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        db.update_document_status(document_id, "failed")
        raise HTTPException(status_code=500, detail=f"Document processing failed: {e}")


@app.get("/documents")
def list_documents():
    """List all uploaded documents."""
    documents = db.get_documents()
    return {"documents": documents}


# --- Validation Endpoints ---

@app.post("/process-input", response_model=ProcessInputResponse)
def process_input(request: ProcessInputRequest):
    """Process user input through the validation pipeline.

    Executes: Input → Claims → Retrieval → Verification → Explanation → Output
    All output is validated via Pydantic BEFORE storage.
    """
    # Check if documents exist
    documents = db.get_documents()
    ready_docs = [d for d in documents if d.get("status") == "ready"]
    if not ready_docs:
        raise HTTPException(
            status_code=400,
            detail="No knowledge base available. Please upload documents first.",
        )

    try:
        # Execute pipeline
        result = pipeline.execute(request.input_text)

        # Create session
        session_id = db.create_session(
            input_text=request.input_text,
            input_type=result.get("input_type", "answer"),
        )

        claims = result.get("claims", [])

        if not claims:
            return ProcessInputResponse(
                session_id=session_id,
                input_type=result.get("input_type", "answer"),
                claims=[],
                message=result.get("message", "No claims extracted."),
            )

        # Validate ALL claims via ClaimResult Pydantic model BEFORE storage
        claim_results: list[ClaimResult] = []
        for c in claims:
            try:
                evidence_items = [
                    EvidenceItem(
                        snippet=e.get("snippet", ""),
                        page_number=e.get("page_number", 0),
                    )
                    for e in c.get("evidence", [])
                ]
                validated_claim = ClaimResult(
                    claim_id=c["claim_id"],
                    claim_text=c["claim_text"],
                    status=c.get("status", "unsupported"),
                    confidence_score=c.get("confidence_score", 0.0),
                    evidence=evidence_items,
                    explanation=c.get("explanation", ""),
                )
                claim_results.append(validated_claim)
            except ValidationError as ve:
                raise HTTPException(
                    status_code=500,
                    detail=f"Pipeline output validation failed for claim {c.get('claim_id', '?')}: {ve}",
                )

        # Store ONLY validated data
        db.insert_claims(
            session_id=session_id,
            claims=[
                {"claim_id": cr.claim_id, "claim_text": cr.claim_text}
                for cr in claim_results
            ],
        )

        db.insert_results(
            session_id=session_id,
            results=[cr.model_dump() for cr in claim_results],
        )

        return ProcessInputResponse(
            session_id=session_id,
            input_type=result.get("input_type", "answer"),
            claims=claim_results,
        )

    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))


# --- Stress Test Endpoint ---

@app.post("/evaluate-reasoning", response_model=EvaluateReasoningResponse)
def evaluate_reasoning(request: EvaluateReasoningRequest):
    """Stress-test student reasoning to expose weaknesses and fragility.

    This is NOT a tutoring endpoint. It actively tries to break the
    student's reasoning by generating adversarial scenarios, detecting
    failure points, and producing targeted challenge questions.

    Executes: Input → Claims → Retrieval → Verification → Stress Test
    """
    try:
        result = pipeline.evaluate_reasoning(
            student_answer=request.student_answer,
            problem=request.problem,
        )

        # Validate output via Pydantic
        weakness_items = [
            WeaknessItem(type=w.get("type", ""), detail=w.get("detail", ""))
            for w in result.get("weakness_summary", [])
        ]

        robustness_raw = result.get("robustness_summary", {})
        robustness = RobustnessSummary(
            robustness_score=robustness_raw.get("robustness_score", 0.0),
            summary=robustness_raw.get("summary", ""),
            level=robustness_raw.get("level", "unknown"),
        )

        return EvaluateReasoningResponse(
            stress_test_results=result.get("stress_test_results", []),
            weakness_summary=weakness_items,
            robustness_summary=robustness,
            adversarial_questions=result.get("adversarial_questions", []),
        )

    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))


# --- Results Endpoints ---

@app.get("/get-results/{session_id}")
def get_results(session_id: str):
    """Get validation results for a specific session."""
    session = db.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found.")

    results = db.get_results_by_session(session_id)

    # Validate results via ClaimResult before returning
    validated_results: list[ClaimResult] = []
    for r in results:
        evidence_items = [
            EvidenceItem(snippet=e.get("snippet", ""), page_number=e.get("page_number", 0))
            for e in r.get("evidence", [])
        ]
        validated_results.append(
            ClaimResult(
                claim_id=r.get("claim_id", ""),
                claim_text=r.get("claim_text", ""),
                status=r.get("status", "unsupported"),
                confidence_score=r.get("confidence_score", 0.0),
                evidence=evidence_items,
                explanation=r.get("explanation", ""),
            )
        )

    return {
        "session_id": session_id,
        "input_text": session.get("input_text", ""),
        "input_type": session.get("input_type", ""),
        "claims": [vr.model_dump() for vr in validated_results],
    }


# --- Feedback Endpoints ---

@app.post("/submit-feedback", response_model=FeedbackResponse)
def submit_feedback(request: FeedbackRequest):
    """Submit user feedback (accept/reject) for a claim."""
    # Verify session exists
    session = db.get_session(request.session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found.")

    feedback_id = db.insert_feedback(
        claim_id=request.claim_id,
        session_id=request.session_id,
        decision=request.decision,
    )

    return FeedbackResponse(
        feedback_id=feedback_id,
        message=f"Feedback '{request.decision}' recorded for claim {request.claim_id}.",
    )


@app.post("/edit-claim", response_model=ProcessInputResponse)
def edit_claim(request: EditClaimRequest):
    """Edit a claim and re-run the validation pipeline for it.

    Output is validated via Pydantic BEFORE storage.
    """
    # Verify session exists
    session = db.get_session(request.session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found.")

    try:
        # Re-run pipeline for the edited claim text
        result = pipeline.execute(request.new_claim_text)

        claims = result.get("claims", [])

        # Validate ALL claims via ClaimResult BEFORE storage
        claim_results: list[ClaimResult] = []
        for c in claims:
            try:
                evidence_items = [
                    EvidenceItem(
                        snippet=e.get("snippet", ""),
                        page_number=e.get("page_number", 0),
                    )
                    for e in c.get("evidence", [])
                ]
                validated_claim = ClaimResult(
                    claim_id=c["claim_id"],
                    claim_text=c["claim_text"],
                    status=c.get("status", "unsupported"),
                    confidence_score=c.get("confidence_score", 0.0),
                    evidence=evidence_items,
                    explanation=c.get("explanation", ""),
                )
                claim_results.append(validated_claim)
            except ValidationError as ve:
                raise HTTPException(
                    status_code=500,
                    detail=f"Pipeline output validation failed: {ve}",
                )

        if claim_results:
            db.insert_claims(
                session_id=request.session_id,
                claims=[
                    {"claim_id": cr.claim_id, "claim_text": cr.claim_text}
                    for cr in claim_results
                ],
            )
            db.insert_results(
                session_id=request.session_id,
                results=[cr.model_dump() for cr in claim_results],
            )

        return ProcessInputResponse(
            session_id=request.session_id,
            input_type=result.get("input_type", "answer"),
            claims=claim_results,
        )

    except (ValueError, RuntimeError) as e:
        raise HTTPException(status_code=500, detail=str(e))


# --- History Endpoints ---

@app.get("/history", response_model=HistoryResponse)
def get_history():
    """Retrieve complete validation history — fully typed, no loose dicts."""
    raw_history = db.get_history()

    sessions: list[HistorySession] = []
    for s in raw_history:
        # Validate claims
        typed_claims = [
            HistoryClaimItem(
                claim_id=c.get("claim_id", ""),
                session_id=c.get("session_id", ""),
                claim_text=c.get("claim_text", ""),
            )
            for c in s.get("claims", [])
        ]

        # Validate results
        typed_results: list[ClaimResult] = []
        for r in s.get("results", []):
            evidence_items = [
                EvidenceItem(snippet=e.get("snippet", ""), page_number=e.get("page_number", 0))
                for e in r.get("evidence", [])
            ]
            typed_results.append(
                ClaimResult(
                    claim_id=r.get("claim_id", ""),
                    claim_text=r.get("claim_text", ""),
                    status=r.get("status", "unsupported"),
                    confidence_score=r.get("confidence_score", 0.0),
                    evidence=evidence_items,
                    explanation=r.get("explanation", ""),
                )
            )

        # Validate feedback
        typed_feedback = [
            HistoryFeedbackItem(
                feedback_id=f.get("feedback_id", ""),
                claim_id=f.get("claim_id", ""),
                session_id=f.get("session_id", ""),
                user_decision=f.get("user_decision", ""),
                created_at=f.get("created_at", ""),
            )
            for f in s.get("feedback", [])
        ]

        sessions.append(
            HistorySession(
                session_id=s.get("session_id", ""),
                input_text=s.get("input_text", ""),
                input_type=s.get("input_type"),
                created_at=s.get("created_at", ""),
                claims=typed_claims,
                results=typed_results,
                feedback=typed_feedback,
            )
        )

    return HistoryResponse(sessions=sessions)
